### ISSUE TITLE
Cross-compilation fails

### ISSUE THREAD

**Issue by ghost** [meh/rust-xkbcommon-sys#1]
When I try to compile for x86_64-unknown-linux-musl I get the following:
Caused by:
  process didn't exit successfully: `/home/nifker/Entwicklung/rust_minifb/target/debug/build/xkbcommon-sys-f9310fdc8120bb79/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CrossCompilation', src/libcore/result.rs:1189:5

Is there any reason I cant cross-compile this crate?

**Comment by meh** [comment]
I'm not sure what's causing that error, maybe because of pkg-config?

**Comment by ghost** [comment]
Should be coming from here: https://github.com/meh/rust-xkbcommon-sys/blob/master/build.rs#L19
Ill try to find out more.

**Comment by ghost** [comment]
Could it be that I need to manually build xkbcommon for musl?

**Comment by meh** [comment]
That's possible, or you might have to install it in a way pkg-config sees it.

**Comment by chaozju** [comment]
> Could it be that I need to manually build xkbcommon for musl?
@meh 

Sorry but may I get further guidance from you on fixing this PLZ? I ran across this issue while cross compiling to RISCV.
THX

**Comment by ghost** [comment]
@chaozju I think when compiling it you need to link against musl. But I havent done it yet, so I cant say much about it.
